---
- name: Copy snipet to protect for DNS rebinding
  become: true
  ansible.builtin.template:
    src: 'templates/snippets/private-addresses.conf'
    dest: '/etc/unbound/unbound.conf.d/'
    owner: root
    group: root
    mode: 'u=rw,g=r,o=r'
  notify: 'Systemctl restart unbound'
  when: unbount__dns_rebind_protection | bool

- name: Copy snipet for qname privacy
  become: true
  ansible.builtin.template:
    src: 'templates/snippets/qname-minimisation.conf'
    dest: '/etc/unbound/unbound.conf.d/'
    owner: root
    group: root
    mode: 'u=rw,g=r,o=r'
  notify: 'Systemctl restart unbound'
  when: unbount__dns_qname_minimisation | bool

- name: Copy anchor snippet
  become: true
  ansible.builtin.template:
    src: 'templates/snippets/root-auto-trust-anchor-file.conf'
    dest: '/etc/unbound/unbound.conf.d/'
    owner: root
    group: root
    mode: 'u=rw,g=r,o=r'
  notify: 'Systemctl restart unbound'
  when: unbound__auto_trust_anchor | bool

- name: Copy local-data entries
  become: true
  ansible.builtin.template:
    src: 'templates/snippets/local-data.conf'
    dest: '/etc/unbound/unbound.conf.d/'
    owner: root
    group: root
    mode: 'u=rw,g=r,o=r'
  notify: 'Systemctl restart unbound'
  when: unbound__local_data is defined and unbound__local_data | length > 0

- name: Ensure local-data config file state
  become: true
  ansible.builtin.file:
    path: '/etc/unbound/unbound.conf.d/local-data.conf'
    state: absent
  notify: 'Systemctl restart unbound'
  when: unbound__local_data is not defined or unbound__local_data | length == 0

- name: Transfer main unbound configuration
  become: true
  ansible.builtin.template:
    src: 'templates/unbound.conf'
    dest: '/etc/unbound/unbound.conf'
    owner: root
    group: root
    mode: 'u=rw,g=r,o=r'
    validate: unbound-checkconf %s
  notify: 'Systemctl restart unbound'
...
