---
- name: Run optional versionscheck
  ansible.builtin.include_tasks: versioncheck.yml
  when: submodules_versioncheck|bool

- name: Install unbound
  ansible.builtin.include_tasks: install.yml

- name: Configure unbound
  ansible.builtin.include_tasks: configure.yml
